# Generated by Django 4.2.7 on 2026-01-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='faculty',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science')], default='Arts', max_length=50),
        ),
    ]
