# Generated by Django 4.2.7 on 2026-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='faculty',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Commerce', 'Commerce'), ('Science', 'Science')], default='Science', max_length=50),
        ),
    ]
